version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: starburger
      POSTGRES_USER: staruser
      POSTGRES_PASSWORD: vfperfectp18121
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U staruser -d starburger"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file: .env
    environment:
      STATIC_ROOT: /app/staticfiles
      MEDIA_ROOT: /app/media
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/static:ro
      - ./media:/media:ro
    restart: unless-stopped

volumes:
  pgdata:
